<div class="tag_title">
	<div class="container">
		<div class="row">
			<div class="col s12">
				<div class="title_page1">PRODUTOS</div>
			</div>
		</div>
	</div>
</div>


<?php if ( $produtos ) : ?>

<div class="container pt-3 pb-3" style="min-height: 730px;">

	<div class="row">

		<div class="col s12">

			<div class="sidebar-left sidebar-fixed">
				<div class="sidebar">
					<div class="sidebar-content">
						<div id="sidebar-list" class="sidebar-menu list-group position-relative animate fadeLeft delay-1">
							<div class="sidebar-list-padding app-sidebar" id="contact-sidenav">
								<ul id="filters" class="button-group contact-list display-grid">
									<li class="sidebar-title">Categorias</li>
									<li class="">
										<label data-filter="*">
											<input type="radio" name="categoria" id="" checked="checked">
											<span>
												Exibir tudo
											</span>
										</label>
									</li>
									<?php foreach($categorias as $categoria) : ?>
									<li class="">
										<label data-filter=".<?= limpa_string($categoria -> categoria); ?>">
											<input type="radio" name="categoria" id="">
											<span>
												<!-- <i class="material-icons mr-2"> star_border </i> -->
												<?= $categoria -> categoria; ?>
											</span>
										</label>
									</li>
									<?php endforeach; ?>
								</ul>
							</div>
						</div>
						<a href="#" data-target="contact-sidenav" class="sidenav-trigger hide-on-large-only"><i class="material-icons">menu</i></a>
					</div>
				</div>
			</div>

		</div>

		<div class="content-area content-right">

			<div id="produtos" class="row">

				<!-- PRODUTO -->
				<?php foreach ( $produtos as $row ) : ?>

				<div class="col s6 m4 l4 produtos <?= limpa_string($row -> categoria); ?>" data-category="<?= limpa_string($row -> categoria); ?>">

					<div class="card">

						<a href="<?= base_url(); ?>produtos/<?= $row -> id; ?>">

							<div class="card-content black-text center-align">

								<div class="card-image">
									<img src="<?= $row -> imagem; ?>" class="">
								</div>

								<div class="card-title"><?= $row -> nome; ?></div>
								<p>
									<?= $row -> categoria; ?>
								</p>

							</div>

						</a>

					</div>

				</div>

				<?php endforeach; ?>

			</div>

		</div>

	</div>

</div>

<?php else : ?>

<div class="container">

	<div class="row">
		<div class="col s12 mt-5 mb-10">
			<h3>Nenhum produto cadastrado no momento.</h3>
		</div>
	</div>

</div>

<?php endif; ?>

<?php require VIEWSPATH . 'distribuidor/section.phtml'; ?>
