<div class="container_right panel">

	<div class="title_pg f_avante">
		<!-- Header search bar starts -->
		<div class="mr-2">Intenções de Compra - Lista</div>
		<div class="input-field outlined">
			<i class="material-icons prefix">search</i>
			<input type="search" class="dataTable_search white-text" placeholder="Pesquisar intenções">
		</div>
	</div>
	<!-- Header search bar Ends -->

	<!-- BEGIN panel-content -->
	<div class="panel-content">

		<div class="panel-header no-border">

			<!-- Botoões Adicionar e Listar -->
			<div class="toolbar bts_acao f_bebas">

				<div class="buttons">
					<div class="buttons hide-buttons">
						<button class="btn btn-large update waves-effect" name="status" value="0" data-tooltip="" data-on="Bloquear" data-off="Desbloquear" data-link="<?= base_url(); ?>intencoes/status">
							<i class="material-icons" data-on="lock" data-off="lock_open"></i>
						</button>
						<button class="btn btn-large excluir waves-effect" disabled="disabled" data-link="<?= base_url(); ?>intencoes" style="border: none">
							<i class="material-icons">delete_forever</i>
						</button>
						<div class="divider"></div>
						<div class="buttons selecteds-label white-text"> </div>
					</div>
				</div>

			</div>

		</div>

		<!-- BEGIN panel-body -->
		<div class="area_dashboard panel-body p-0">

			<table class="datatable responsiveDatatable" data-link="<?= base_url(); ?>intencoes">
				<thead>
					<tr>
						<th class="disabled white-text" width="1%" data-orderable="false">
							<label>
								<input type="checkbox" class="amber" id="check-all">
								<span> </span>
							</label>
						</th>
						<th class="white-text">#</th>
						<th class="white-text">Cliente</th>
						<th class="white-text">Produto</th>
						<th class="white-text center-align">Data</th>
						<th class="disabled white-text center-align" data-orderable="false"></th>
					</tr>
				</thead>
			</table>

		</div>
		<!-- END panel-body -->

	</div>
	<!-- END panel-content -->

</div>
