<?php 

$records = [];

if ( isset($usuarios) ) {

	$grupo = new \App\Models\AclGrupoModel();

	foreach ( $usuarios -> result() as $row ){
		
		$date = new DateTime($row -> ultimo_login);

		$gp = $grupo -> getAll((int) $row -> id_grupo);
		$nomeGrupo = isset( $gp ) ? $gp -> grupo : '-';

		$records[] = array(
			'<label><input type="checkbox" name="id[]" class="light-blue" value="' . $row -> id . '" data-status="' . $row -> status . '"><span></span></label>',
			$row -> nome,
			$nomeGrupo,
			$row -> email,
			($row -> ultimo_login !== '0000-00-00 00:00:00' ? $date -> format('d/m/Y H:i:s') : 'Nunca' ),
			'<div class="' . ( $row -> status === '0' ? 'blocked' : null) . '">
			<i class="material-icons">' . ( $row -> status === '0' ? 'lock' : 'check') . '</i>
			</div>'
		);

	}

}

echo json_encode([
	'data' => $records,
	'recordsFiltered' => $numRows,
]);