<div class="container_right panel">
	
	<!-- Header search bar starts -->
	<div class="title_pg f_avante" style="place-content: start;">

		<button data-href="<?= base_url(); ?>banners" class="btn btn-flat btn-small btn-floating transparent waves-effect waves-light white-text bt_ac btn-flat mr-1" data-tooltip="Voltar">
			<i class="material-icons">arrow_back</i>
		</button>

		<div class="mr-2">Banners - <?= ! isset($row) ? 'Adicionar' : 'Editar' ?></div>
	
	</div>
	<!-- Header search bar Ends -->

	<!-- BEGIN panel-content -->
	<div class="panel-content">

		<!-- BEGIN panel-header -->
		<div class="panel-header no-border">

			<!-- BEGIN Toolbar -->
			<div class="toolbar bts_acao f_bebas">

				<div class="buttons">

					<!-- BEGIN Lista de Botões -->
					<div class="buttons show-buttons">

						<?php if ( isset($row) ) : ?>
						<button class="btn btn-large excluir waves-effect" value="<?= isset($row) ? $row -> id : null; ?>" data-tooltip="Excluir" data-link="<?= base_url(); ?>banners" style="border: none">
							<i class="material-icons">delete_forever</i>
						</button>
						<div class="divider"></div>
						<?php endif; ?>

					</div>
					<!-- END Lista de Botões -->

				</div>

			</div>
			<!-- END Toolbar -->

		</div>
		<!-- END panel-header -->

		<!-- BEGIN panel-body -->
		<div class="area_dashboard panel-body pl-0 pr-0 pt-1">

            <?php $tmpl = fopen(VIEWSPATH . 'email/template_email.html', 'r'); $le = fread($tmpl, 2024); $data = explode('<>', $le); ?>
            <textarea class="basic--editor"><?= implode("", $data); ?></textarea>

            <?php fclose($tmpl); ?>

        </div>
        <!-- END panel-body -->

    </div>

</div>