<div class="tag_title">
	<div class="container">
		<div class="row">
			<div class="col s12">
				<div class="title_page1">CONTATO</div>
			</div>
		</div>
	</div>
</div>

<div class="container pt-3 pb-3" style="min-height: 600px;">

	<div class="row">

		<div class="col s12">

			<?php if ( ! empty( configuracoes('contato_imagem', 'tb_empresa') ) ) : ?>
			<div class="img_empresa">
				<img src="<?= configuracoes('contato_imagem', 'tb_empresa'); ?>" class="img_cem">
			</div>
			<?php endif; ?>

			<div class="info_empresa">

				<div class="title1_empresa">FALE CONOSCO</div>
				<div class="title2_empresa">PREENCHA O FORMULÁRIO ABAIXO E NOS ENVIE</div>

				<form method="post" action="<?= base_url(); ?>contato" novalidate autocomplete="off">

					<div class="row">
						<div class="col s12">
							<div class="input-field">
								<input type="text" name="nome" class="input_form grey border-radius-1 grey lighten-2" placeholder="Seu nome" required>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col s12">
							<div class="input-field">
								<input type="email" name="email" class="input_form grey border-radius-1 grey lighten-2" placeholder="Seu e-mail" required>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col s12">
							<div class="input-field">
								<input type="number" name="telefone" class="input_form grey border-radius-1 grey lighten-2" placeholder="Seu Telefone" required>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col s12">
							<div class="input-field">
								<input type="text" name="assunto" class="input_form grey border-radius-1 grey lighten-2" placeholder="Assunto" required>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col s12">
							<div class="input-field">
								<textarea name="mensagem" class="editor--hide_toolbar materialize-textarea border-radius-1 grey lighten-2" placeholder="Escreva a sua mensagem aqui" style="font-family: sans-serif !important"></textarea>
							</div>
						</div>
					</div>
					<div class="row"> 
						<div class="col s12">
							<div class="input-field z-depth-2">
								<button type="submit" class="btn btn-large col gradient-45deg-darken-pink-pink waves-effect waves-light">
									Enviar
								</button>
							</div>
						</div>
					</div>
					<input type="hidden" name="_method" value="post">
				</form>

			</div>

		</div>

	</div>
</div>

<?php require VIEWSPATH . 'contato/section.phtml'; ?>


<!--Google Maps-->
<div class="mapag">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1315.1283705198737!2d-50.4258596078572!3d-21.20229624860985!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9496415a03ef5e89%3A0x6de181779a029358!2sR.%20S%C3%A3o%20Domingos%20-%20Santa%20Luzia%2C%20Ara%C3%A7atuba%20-%20SP!5e0!3m2!1spt-BR!2sbr!4v1600775797319!5m2!1spt-BR!2sbr" class="size_map" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</div>
