<script>
var BASE_URL  = '<?= base_url(); ?>';
var BASE_PATH = '<?= base_path(); ?>';
</script>

<!-- plugins | jQuery/Materialize -->
<script src="<?= base_path(); ?>plugins/jquery/jquery-3.5.1.min.js"></script>
<script src="<?= base_path(); ?>plugins/pace/pace.min.js"></script>
<script src="<?= base_path(); ?>plugins/materializecss/materialize.min.js"></script>
<script src="<?= base_path(); ?>plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="<?= base_path(); ?>plugins/jquery/form.js"></script>
<script src="<?= base_path(); ?>plugins/datatable/v10.2/jquery.dataTables.min.js"></script>
<script src="<?= base_path(); ?>plugins/isotope/js/isotope.min.js"></script>

<script src="<?= base_path(); ?>plugins/quill/js/katex.min.js"></script>
<script src="<?= base_path(); ?>plugins/quill/js/highlight.min.js"></script>
<script src="<?= base_path(); ?>plugins/quill/js/quill.min.js"></script>
<script src="<?= base_path(); ?>plugins/tinymce/tinymce.min.js"></script>

<!-- scripts | Padrão -->
<script src="<?= base_path(); ?>scripts/materializecss.js"></script>
<script src="<?= base_path(); ?>scripts/datatables.js"></script>
<script src="<?= base_path(); ?>scripts/storage.js"></script>
<script src="<?= base_path(); ?>scripts/functions.js"></script>
<script src="<?= base_path(); ?>scripts/http/http.js"></script>
<script src="<?= base_path(); ?>scripts/http/request.js"></script>
<script src="<?= base_path(); ?>scripts/form.js"></script>

<script src="<?= base_path(); ?>scripts/core.js"></script>
