<!-- fonts -->
<link rel="stylesheet" media="screen" href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
<link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap">

<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/material-icons/material-icons.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/muli/muli.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/roboto/roboto.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>fonts/icons/icons.css">

<!-- styles -->
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/animate.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/materializecss/materialize.min.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/perfect-scrollbar/perfect-scrollbar.css">

<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/datatable/v10.2/jquery.dataTables.min.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/datatable/v10.2/responsive.dataTables.min.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/datatable/v10.2/datatables.min.css">

<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/quill/css/katex.min.css" />
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/quill/css/monokai-sublime.min.css" />
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/quill/css/quill.snow.css" />
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>plugins/quill/css/quill.bubble.css" />

<!-- others styles -->
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/colors.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/style.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/app-sidebar.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/main/themes/default.css">

<!-- site styles -->
<link rel="stylesheet" media="screen" href="<?= base_path(true); ?>styles/layout.css">
<link rel="stylesheet" media="screen" href="<?= base_path(true); ?>styles/lightbox.css">
<link rel="stylesheet" media="screen" href="<?= base_path(true); ?>styles/sss.css">
<link rel="stylesheet" media="screen" href="<?= base_path(true); ?>styles/css3.css">
<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/alteracoes.css">
