<section class="area_distribuidor">
	<div class="container">
		<div class="title_2">SEJA UM DISTRIBUIDOR</div>
		<div class="text_dist">
			Para ser um distribuidor RABONI COSMÉTICOS, entre em contato conosco,
			acesse um de nossos canais de comunicação, nosso ícone do WhatsApp,
		</div>
		<div class="contato_dist">
			<a href="<?= ! empty($redes_sociais['email']) ? 'https://wa.me/' . $redes_sociais['whatsapp'] : '#'; ?>" target="_blank">
				<div class="icon_dist">
					<img src="<?= base_path(true); ?>img/icons/icon_whats_b.png" class="img_cem">
				</div>
			</a>

			<a href="<?= ! empty($redes_sociais['email']) ? 'mailto://' . $redes_sociais['email'] : '#'; ?>">
				<div class="icon_dist">
					<img src="<?= base_path(true); ?>img/icons/icon_envelope_b.png" class="img_cem">
				</div>
			</a>

			<a href="<?= $redes_sociais['facebook'] ?? '#'; ?>" target="_blank">
				<div class="icon_dist">
					<img src="<?= base_path(true); ?>img/icons/icon_face_b.png" class="img_cem">
				</div>
			</a>

			<a href="<?= $redes_sociais['instagram'] ?? '#'; ?>" target="_blank">
				<div class="icon_dist">
					<img src="<?= base_path(true); ?>img/icons/icon_insta_b.png" class="img_cem">
				</div>
			</a>
		</div>
	</div>
</section>
