<div class="tag_title">
	<div class="container">
		<div class="row">
			<div class="col s12">
				<div class="title_page1">QUEM SOMOS</div>
			</div>
		</div>
	</div>
</div>


<div class="container pt-3 pb-3">

	<div class="row">

		<div class="col s12">
			<div class="img_empresa">
				<img src="<?= base_path(true); ?>img/img_empresa.jpg" class="img_cem">
			</div>
			<div class="info_empresa">
				<div class="title1_empresa">NOSSA HISTÓRIA</div>
				<div class="title2_empresa">VOCÊ FAZ PARTE DO NOSSO SUCESSO!</div>
				<div class="text_empresa">
					<?= configuracoes('quem_somos', 'tb_empresa');?>
				</div>
			</div>
		</div>

	</div>

</div>

<?php require VIEWSPATH . 'distribuidor/section.phtml'; ?>