<h3> Olá, {nome}</h3>

<p>
    Sua conta foi criada/atualizada no site
    <strong>
        <a href="#"
            target="_blank"> Teste</a>
    </strong> pelo Administrador.
</p>

<p>Abaixo seguem as informações de acesso para sua área de administração.</p>

<p>
    Seu Login: <strong><a> {email} </a></strong>
    <br> Sua senha: <strong><a>{senha}</a></strong>
    <br>
</p>

<p>
    Obrigado.
    <br>
    <br> Equipe {+ configuracoes url +}
</p>
<a href="#" target="_blank">Acessar Agora</a>
