<body>

	<div id="body">

		<?php
		$page = basename($_SERVER['REQUEST_URI']);
		$css_page_file =  base_path() . 'styles/admin/themes/pages' . DS . $page . '.css';
		?>

		<?php if ( file_exists( $_SERVER['DOCUMENT_ROOT'] . $css_page_file) ) : ?>
		<link rel="stylesheet" media="screen" href="<?= $css_page_file; ?>">
		<?php endif; ?>

		<?php if ( ! isset($_SESSION[USERDATA]['passthru']) ) : ?>
		<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/admin/themes/pages/login/login.css">
		<?php endif; ?>

		<?= $header; ?>

		<?= $sidebar; ?>

		<!-- BEGIN #main -->
		<div id="main">

			<?= $view; ?>

		</div>
		<!-- END #main -->

		<?= $footer; ?>

	</div>

	<?php require('includes/scripts.phtml'); ?>

</body>
