<body class="theme-default vertical-layout">

	<div class="carregando" id="carregando" style="z-index: 999999999;">
		<div class="logo_carregando">
			<img src="<?= base_path(true); ?>img/logo_carregando.png" class="img_cem"><br>
			<div class="loading_gif"><img src="<?= base_path(true); ?>img/loading.gif" class="img_cem"></div>
		</div>
	</div>

	<div id="body">

		<?php
	$page = basename($_SERVER['REQUEST_URI']);
	$css_page_file =  base_path() . 'styles/main/themes/pages' . DS . $page . '.css';
	?>

		<?php if ( file_exists( $_SERVER['DOCUMENT_ROOT'] . $css_page_file) ) : ?>
		<link rel="stylesheet" media="screen" href="<?= $css_page_file; ?>">
		<?php endif; ?>

		<?php if ( ! isset($_SESSION[USERDATA]['passthru']) ) : ?>
		<link rel="stylesheet" media="screen" href="<?= base_path(); ?>styles/main/themes/pages/login/login.css">
		<?php endif; ?>

		<?= $header; ?>

		<?= $sidebar; ?>

		<!-- BEGIN #main -->
		<div id="main" class="<?php configuracoes('status', 'tb_acl_usuario') === '1' ? 'main-full' : null; ?>">

			<!-- BEGIN container -->
			<div class="">

				<!-- BEGIN row -->
				<div class="">

					<!-- BEGIN col.s12 -->
					<div class="">

						<?= $view; ?>

					</div>
					<!-- END col.s12 -->

				</div>
				<!-- END row -->

			</div>
			<!-- END container -->

			<div class="content-overlay"></div>

		</div>
		<!-- END #main -->

		<?= $footer; ?>

	</div>

	<?php require('includes/scripts.phtml'); ?>

</body>
