<footer>
	<div class="container">
		<div class="row">
			<div class="col s12">
				<div class="logo_footer">
					<img src="{+ base_path true +}img/logo_footer.png" class="img_cem">
				</div>
				<div class="copyright">Raboni Cosméticos {year}. Todos os direitos reservados.</div>
				<div class="dev">
					<a href="http://www.tacticweb.com.br" target="_blank">
						<div class="tw"></div>
					</a>
				</div>
			</div>
		</div>
</footer>

<!--Whatsapp-->
<?php if ( ! empty($redes_sociais['whatsapp']) ) : ?>
<a href="<?= 'https://wa.me/' . limpa_string($redes_sociais['whatsapp'], ''); ?>" target="_blank">
	<span class="wp">
		<img src="{+ base_path true +}img/icons/icon_whats.png" class="img_cem">
	</span>
</a>
<?php endif; ?>
