<header>

	<!--header-->
	<div class="container">
		<nav class="menu1">
			<a href="{+ base_url +}home">
				<span class="lk">HOME</span>
			</a>
			<a href="{+ base_url +}quemsomos">
				<span class="lk">QUEM SOMOS</span>
			</a>
			<a href="{+ base_url +}produtos">
				<span class="lk">PRODUTOS</span>
			</a>
		</nav>
		<div class="shadow_l">
			<img src="{+ base_path true +}img/shadow_left.png" class="img_cem">
		</div>
		<div class="logo">
			<img src="{+ base_path true +}img/logo.png" class="img_cem">
		</div>
		<div class="shadow_r">
			<img src="{+ base_path true +}img/shadow_right.png" class="img_cem">
		</div>
		<nav class="menu2">
			<a href="{+ base_url +}distribuidor"><span class="lk">DISTRIBUIDOR</span></a>
			<a href="{+ base_url +}contato"><span class="lk">CONTATO</span></a>
			<span class="social">
				<a href="{facebook}" target="_blank"><span class="icon_social"><img src="{+ base_path true +}img/icons/icon_face.png" class="img_cem"></span></a>
				<a href="{instagram}" target="_blank"><span class="icon_social"><img src="{+ base_path true +}img/icons/icon_insta.png" class="img_cem"></span></a>
			</span>
		</nav>
	</div>

	<!--botão mobile-->
	<div class="bt_menu_mob" data-element=".menu_mob" id="bt_menu">
		<img src="{+ base_path true +}img/bt_mob.png" class="img_cem">
	</div>

</header>

<!--menu mobile-->
<div class="menu_mob">
	<ul>
		<li>
			<a href="{+ base_url +}home">
				<div class="lk_mob">Home</div>
			</a>
		</li>
		<li>
			<a href="{+ base_url +}quemsomos">
				<div class="lk_mob">Quem Somos</div>
			</a>
		</li>
		<li>
			<a href="{+ base_url +}produtos"><div class="lk_mob">Produtos</div></a>
		</li>
		<li>
			<a href="{+ base_url +}distribuidor">
				<div class="lk_mob">Distribuidor</div>
			</a>
		</li>
		<li>
			<a href="{+ base_url +}contato">
				<div class="lk_mob">Contato</div>
			</a>
		</li>
		<div class="social">
			<a href="{facebook}" target="_blank">
				<div class="icon_social"><img src="{+ base_path true +}img/icons/icon_face_b.png" class="img_cem"></div>
			</a>
			<a href="{instagram}" target="_blank">
				<div class="icon_social"><img src="{+ base_path true +}img/icons/icon_insta_b.png" class="img_cem"></div>
			</a>
		</div>
	</ul>
</div>

