<div class="container_right">

	<!-- Header search bar starts -->
	<div class="title_pg f_avante">

		<div class="mr-2">Quem Somos</div>

	</div>
	<!-- Header search bar Ends -->

	<!-- BEGIN panel-content -->
	<div class="panel-content">

		<!-- BEGIN panel-header -->
		<div class="panel-header no-border">

			<!-- BEGIN Toolbar -->
			<div class="toolbar bts_acao f_bebas">

			</div>
			<!-- END Toolbar -->

		</div>
		<!-- END panel-header -->

		<!-- BEGIN panel-body -->
		<div class="area_dashboard panel-body pl-0 pr-0 pt-1">

			<form method="post" autocomplete="off" novalidate action="<?= base_url(); ?>quemsomos">

				<div class="row">

					<!-- BEGIN Input[telefone] -->
					<div class="col s12 l6 pl-0">
						<div class="input-field amber-text mb-2">
							<label class="grey-text">Telefone</label>
							<input type="tel" name="telefone" class="amber-border white-text" maxlength="16" value="<?= isset($row) ? $row -> telefone : null; ?>">
						</div>
					</div>
					<!-- END Input[telefone] -->

					<!-- BEGIN Input[celular] -->
					<div class="col s12 l6 pr-0">
						<div class="input-field amber-text mb-2">
							<label class="grey-text">Celular / Whatsapp</label>
							<input type="tel" name="celular" class="amber-border white-text" maxlength="16" value="<?= isset($row) ? $row -> celular : null; ?>">
						</div>
					</div>
					<!-- END Input[E-mail] -->

				</div>


				<div class="row">

				</div>

				<div class="row">

					<!-- BEGIN Input[Instagram] -->
					<div class="col s12 l6 pl-0">
						<div class="input-field">
							<label class="grey-text">Instagram</label>
							<input type="url" name="instagram" class="amber-border white-text" maxlength="160" value="<?= isset($row) ? $row -> instagram : null; ?>">
							<!-- <div class="helper-text left amber-text">Informe apenas o usuário do Instagram</div> -->
						</div>
					</div>
					<!-- END Input[Instagram] -->

					<!-- BEGIN Input[Facebook] -->
					<div class="col s12 l6 pr-0">
						<div class="input-field amber-text mb-2">
							<label class="grey-text">Facebook</label>
							<input type="url" name="facebook" class="amber-border white-text" maxlength="160" value="<?= isset($row) ? $row -> facebook : null; ?>">
							<!-- <div class="helper-text left amber-text">Informe apenas o usuário do Facebook</div> -->
						</div>
					</div>
					<!-- END Input[Facebook] -->

				</div>

				<div class="row">

					<!-- BEGIN Input[E-mail] -->
					<div class="col s12 l6 pl-0">
						<div class="input-field amber-text">
							<label class="grey-text">E-mail</label>
							<input type="url" name="email" class="amber-border white-text" maxlength="160" value="<?= isset($row) ? $row -> email : null; ?>">
						</div>
					</div>
					<!-- END Input[E-mail] -->

					<!-- BEGIN Input[LinkedIn] -->
					<div class="col s12 l6 pr-0">
						<div class="input-field">
							<label class="grey-text">LinkedIn</label>
							<input type="url" name="linkedin" class="amber-border white-text" maxlength="160" value="<?= isset($row) ? $row -> linkedin : null; ?>">
						</div>
					</div>
					<!-- END Input[LinkedIn] -->

				</div>

				<div class="row">

					<!-- BEGIN Input[Google+] -->
					<div class="col s12 l6 pl-0">
						<div class="input-field">
							<label class="grey-text">Google+</label>
							<input type="url" name="gplus" class="amber-border white-text" maxlength="160" value="<?= isset($row) ? $row -> gplus : null; ?>">
						</div>
					</div>
					<!-- END Input[Google+] -->

					<!-- BEGIN Input[GoogleMaps] -->
					<div class="col s12 l6 pr-0">
						<div class="input-field">
							<label class="grey-text">Google Maps</label>
							<input type="url" name="gmaps" class="amber-border white-text" maxlength="160" value="<?= isset($row) ? $row -> gmaps : null; ?>">
						</div>
					</div>
					<!-- END Input[GoogleMaps] -->

				</div>

				<div class="row">

					<!-- BEGIN Input[GoogleMaps] -->
					<div class="col s12 pl-0 pr-0 mb-1">
						<div class="input-field pt-1">
							<label class="grey-text active">Imagem da página de quem somos</label>
							<div class="media conj_img_edit">
								<div class="img_icon_pdf image_view z-depth-4 material-icons">
									<?php if ( isset($row) && $row -> quem_somos_imagem ) : ?>
									<img src="<?= $row -> quem_somos_imagem; ?>" class="img_cem materialboxed original">
									<input type="hidden" name="original_name">
									<?php endif; ?>
								</div>
								<div class="nome_arquivo" data-placeholder="<?= isset($row) && $row -> quem_somos_imagem ? basename($row -> quem_somos_imagem) : 'Selecione uma imagem'; ?>"></div>
								<div class="bt_excluir waves-effect redefinir amber" style="<?= isset($row) && ! empty($row -> quem_somos_imagem) ? 'display: none;' : ''; ?>">
									<i class="material-icons">undo</i>
								</div>
								<div class="btn_add_new_image waves-effect image_alt amber">
									<i class="material-icons">add_photo_alternate</i>
								</div>
								<input type="file" name="quem_somos_imagem" id="quem_somos_imagem" accept="image">
							</div>
						</div>
					</div>
					<!-- END Input[GoogleMaps] -->

				</div>

				<div class="row">

					<!-- BEGIN Input[GoogleMaps] -->
					<div class="col s12 l6 pl-0">
						<div class="input-field pt-1">
							<label class="grey-text active pb-2">Imagem da página de distribuidores</label>
							<div class="media conj_img_edit">
								<div class="img_icon_pdf image_view z-depth-4 material-icons">
									<?php if ( isset($row) && $row -> distribuidor_imagem ) : ?>
									<img src="<?= $row -> distribuidor_imagem; ?>" class="img_cem materialboxed original">
									<input type="hidden" name="original_name">
									<?php endif; ?>
								</div>
								<div class="nome_arquivo" data-placeholder="<?= isset($row) && $row -> distribuidor_imagem ? basename($row -> distribuidor_imagem) : 'Selecione uma imagem'; ?>"></div>
								<div class="bt_excluir waves-effect redefinir amber" style="<?= isset($row) && ! empty($row -> distribuidor_imagem) ? 'display: none;' : ''; ?>">
									<i class="material-icons">undo</i>
								</div>
								<div class="btn_add_new_image waves-effect image_alt amber">
									<i class="material-icons">add_photo_alternate</i>
								</div>
								<input type="file" name="distribuidor_imagem" id="distribuidor_imagem" accept="image">
							</div>
						</div>
					</div>
					<!-- END Input[GoogleMaps] -->

					<!-- BEGIN Input[GoogleMaps] -->
					<div class="col s12 l6 pr-0">
						<div class="input-field pt-1">
							<label class="grey-text active pb-1">Imagem da página de contato</label>
							<div class="media conj_img_edit">
								<div class="img_icon_pdf image_view z-depth-4 material-icons">
									<?php if ( isset($row) && $row -> contato_imagem ) : ?>
									<img src="<?= $row -> contato_imagem; ?>" class="img_cem materialboxed original">
									<input type="hidden" name="original_name">
									<?php endif; ?>
								</div>
								<div class="nome_arquivo" data-placeholder="<?= isset($row) && $row -> contato_imagem ? basename($row -> contato_imagem) : 'Selecione uma imagem'; ?>"></div>
								<div class="bt_excluir waves-effect redefinir amber" style="<?= isset($row) && ! empty($row -> contato_imagem) ? 'display: none;' : ''; ?>">
									<i class="material-icons">undo</i>
								</div>
								<div class="btn_add_new_image waves-effect image_alt amber">
									<i class="material-icons">add_photo_alternate</i>
								</div>
								<input type="file" name="contato_imagem" id="contato_imagem" accept="image">
							</div>
						</div>
					</div>
					<!-- END Input[GoogleMaps] -->
				</div>

				<div class="row">
				</div>

				<div class="row">
				</div>

				<div class="row">

					<!-- BEGIN Input[Quem Somos] -->
					<div class="col s12 pr-0 pl-0">
						<div class="input-field">
							<div class="editor basic--editor" placeholder="História da empresa" style="min-height: 400px;"><?= isset($row) ? $row -> quem_somos : null; ?></div>
							<input type="hidden" name="quem_somos" id="quem_somos">
						</div>
					</div>
					<!-- END Input[Quem Somos] -->

				</div>

				<div class="row">
					<div class="col s12 l6 pl-0">
						<button type="submit" class="amber btn col s12 l6 btn-large black-text waves-effect">SALVAR </button>
					</div>
				</div>

				<input type="hidden" name="acao" value="login">
				<input type="hidden" name="id" value="<?= isset($row) ? $row -> id : null; ?>">
				<input type="hidden" name="_method" value="<?= isset($row) ? 'put' : 'post'; ?>">

			</form>

		</div>

	</div>

</div>
